/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ActionCar model module.
 * @module model/ActionCar
 * @version v1
 */
export class ActionCar {
  /**
   * Constructs a new <code>ActionCar</code>.
   * @alias module:model/ActionCar
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ActionCar</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ActionCar} obj Optional instance to populate.
   * @return {module:model/ActionCar} The populated <code>ActionCar</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ActionCar();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('sharePercentage'))
        obj.sharePercentage = ApiClient.convertToType(data['sharePercentage'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ActionCar.prototype.id = undefined;

/**
 * @member {Number} sharePercentage
 */
ActionCar.prototype.sharePercentage = undefined;

