/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ActionCar} from './ActionCar';
import {ImgCar} from './ImgCar';

/**
 * The Car model module.
 * @module model/Car
 * @version v1
 */
export class Car {
  /**
   * Constructs a new <code>Car</code>.
   * @alias module:model/Car
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Car</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Car} obj Optional instance to populate.
   * @return {module:model/Car} The populated <code>Car</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Car();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('idCarEquipment'))
        obj.idCarEquipment = ApiClient.convertToType(data['idCarEquipment'], 'String');
      if (data.hasOwnProperty('vin'))
        obj.vin = ApiClient.convertToType(data['vin'], 'String');
      if (data.hasOwnProperty('cost'))
        obj.cost = ApiClient.convertToType(data['cost'], 'Number');
      if (data.hasOwnProperty('carMileage'))
        obj.carMileage = ApiClient.convertToType(data['carMileage'], 'Number');
      if (data.hasOwnProperty('dateOfRealeseCar'))
        obj.dateOfRealeseCar = ApiClient.convertToType(data['dateOfRealeseCar'], 'Date');
      if (data.hasOwnProperty('actionCarId'))
        obj.actionCarId = ApiClient.convertToType(data['actionCarId'], 'Number');
      if (data.hasOwnProperty('actionCar'))
        obj.actionCar = ActionCar.constructFromObject(data['actionCar']);
      if (data.hasOwnProperty('isActive'))
        obj.isActive = ApiClient.convertToType(data['isActive'], 'Boolean');
      if (data.hasOwnProperty('isDeleted'))
        obj.isDeleted = ApiClient.convertToType(data['isDeleted'], 'Boolean');
      if (data.hasOwnProperty('imgsCar'))
        obj.imgsCar = ApiClient.convertToType(data['imgsCar'], [ImgCar]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Car.prototype.id = undefined;

/**
 * @member {String} idCarEquipment
 */
Car.prototype.idCarEquipment = undefined;

/**
 * @member {String} vin
 */
Car.prototype.vin = undefined;

/**
 * @member {Number} cost
 */
Car.prototype.cost = undefined;

/**
 * @member {Number} carMileage
 */
Car.prototype.carMileage = undefined;

/**
 * @member {Date} dateOfRealeseCar
 */
Car.prototype.dateOfRealeseCar = undefined;

/**
 * @member {Number} actionCarId
 */
Car.prototype.actionCarId = undefined;

/**
 * @member {module:model/ActionCar} actionCar
 */
Car.prototype.actionCar = undefined;

/**
 * @member {Boolean} isActive
 */
Car.prototype.isActive = undefined;

/**
 * @member {Boolean} isDeleted
 */
Car.prototype.isDeleted = undefined;

/**
 * @member {Array.<module:model/ImgCar>} imgsCar
 */
Car.prototype.imgsCar = undefined;

