/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ValueCarEquipmentDto} from './ValueCarEquipmentDto';

/**
 * The CarEquipmentFormDto model module.
 * @module model/CarEquipmentFormDto
 * @version v1
 */
export class CarEquipmentFormDto {
  /**
   * Constructs a new <code>CarEquipmentFormDto</code>.
   * @alias module:model/CarEquipmentFormDto
   * @class
   * @param equipmentItems {Object.<String, Array.<module:model/ValueCarEquipmentDto>>} 
   */
  constructor(equipmentItems) {
    this.equipmentItems = equipmentItems;
  }

  /**
   * Constructs a <code>CarEquipmentFormDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CarEquipmentFormDto} obj Optional instance to populate.
   * @return {module:model/CarEquipmentFormDto} The populated <code>CarEquipmentFormDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CarEquipmentFormDto();
      if (data.hasOwnProperty('equipmentItems'))
        obj.equipmentItems = ApiClient.convertToType(data['equipmentItems'], {'String': [ValueCarEquipmentDto]});
    }
    return obj;
  }
}

/**
 * @member {Object.<String, Array.<module:model/ValueCarEquipmentDto>>} equipmentItems
 */
CarEquipmentFormDto.prototype.equipmentItems = undefined;

