/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ValueCarEquipmentDto} from './ValueCarEquipmentDto';

/**
 * The CarEquipmentFormItemDto model module.
 * @module model/CarEquipmentFormItemDto
 * @version v1
 */
export class CarEquipmentFormItemDto {
  /**
   * Constructs a new <code>CarEquipmentFormItemDto</code>.
   * @alias module:model/CarEquipmentFormItemDto
   * @class
   * @param name {String} 
   * @param equipmentItem {module:model/ValueCarEquipmentDto} 
   */
  constructor(name, equipmentItem) {
    this.name = name;
    this.equipmentItem = equipmentItem;
  }

  /**
   * Constructs a <code>CarEquipmentFormItemDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CarEquipmentFormItemDto} obj Optional instance to populate.
   * @return {module:model/CarEquipmentFormItemDto} The populated <code>CarEquipmentFormItemDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CarEquipmentFormItemDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('equipmentItem'))
        obj.equipmentItem = ValueCarEquipmentDto.constructFromObject(data['equipmentItem']);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
CarEquipmentFormItemDto.prototype.name = undefined;

/**
 * @member {module:model/ValueCarEquipmentDto} equipmentItem
 */
CarEquipmentFormItemDto.prototype.equipmentItem = undefined;

