/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ValueCarEquipment} from './ValueCarEquipment';

/**
 * The CarEquipmentFormItem model module.
 * @module model/CarEquipmentFormItem
 * @version v1
 */
export class CarEquipmentFormItem {
  /**
   * Constructs a new <code>CarEquipmentFormItem</code>.
   * @alias module:model/CarEquipmentFormItem
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CarEquipmentFormItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CarEquipmentFormItem} obj Optional instance to populate.
   * @return {module:model/CarEquipmentFormItem} The populated <code>CarEquipmentFormItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CarEquipmentFormItem();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('equipmentItem'))
        obj.equipmentItem = ValueCarEquipment.constructFromObject(data['equipmentItem']);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
CarEquipmentFormItem.prototype.name = undefined;

/**
 * @member {module:model/ValueCarEquipment} equipmentItem
 */
CarEquipmentFormItem.prototype.equipmentItem = undefined;

