/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CarEquipmentFormItem} from './CarEquipmentFormItem';

/**
 * The CarEquipment model module.
 * @module model/CarEquipment
 * @version v1
 */
export class CarEquipment {
  /**
   * Constructs a new <code>CarEquipment</code>.
   * @alias module:model/CarEquipment
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CarEquipment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CarEquipment} obj Optional instance to populate.
   * @return {module:model/CarEquipment} The populated <code>CarEquipment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CarEquipment();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('isDeleted'))
        obj.isDeleted = ApiClient.convertToType(data['isDeleted'], 'Boolean');
      if (data.hasOwnProperty('equipments'))
        obj.equipments = ApiClient.convertToType(data['equipments'], [CarEquipmentFormItem]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
CarEquipment.prototype.id = undefined;

/**
 * @member {String} name
 */
CarEquipment.prototype.name = undefined;

/**
 * @member {Boolean} isDeleted
 */
CarEquipment.prototype.isDeleted = undefined;

/**
 * @member {Array.<module:model/CarEquipmentFormItem>} equipments
 */
CarEquipment.prototype.equipments = undefined;

