/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Car} from './Car';
import {Employee} from './Employee';
import {StateCarRepair} from './StateCarRepair';

/**
 * The CarRepair model module.
 * @module model/CarRepair
 * @version v1
 */
export class CarRepair {
  /**
   * Constructs a new <code>CarRepair</code>.
   * @alias module:model/CarRepair
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CarRepair</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CarRepair} obj Optional instance to populate.
   * @return {module:model/CarRepair} The populated <code>CarRepair</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CarRepair();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('carId'))
        obj.carId = ApiClient.convertToType(data['carId'], 'Number');
      if (data.hasOwnProperty('car'))
        obj.car = Car.constructFromObject(data['car']);
      if (data.hasOwnProperty('employeeId'))
        obj.employeeId = ApiClient.convertToType(data['employeeId'], 'Number');
      if (data.hasOwnProperty('employee'))
        obj.employee = Employee.constructFromObject(data['employee']);
      if (data.hasOwnProperty('startWork'))
        obj.startWork = ApiClient.convertToType(data['startWork'], 'Date');
      if (data.hasOwnProperty('endWork'))
        obj.endWork = ApiClient.convertToType(data['endWork'], 'Date');
      if (data.hasOwnProperty('stateCarRepair'))
        obj.stateCarRepair = StateCarRepair.constructFromObject(data['stateCarRepair']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
CarRepair.prototype.id = undefined;

/**
 * @member {String} description
 */
CarRepair.prototype.description = undefined;

/**
 * @member {Number} carId
 */
CarRepair.prototype.carId = undefined;

/**
 * @member {module:model/Car} car
 */
CarRepair.prototype.car = undefined;

/**
 * @member {Number} employeeId
 */
CarRepair.prototype.employeeId = undefined;

/**
 * @member {module:model/Employee} employee
 */
CarRepair.prototype.employee = undefined;

/**
 * @member {Date} startWork
 */
CarRepair.prototype.startWork = undefined;

/**
 * @member {Date} endWork
 */
CarRepair.prototype.endWork = undefined;

/**
 * @member {module:model/StateCarRepair} stateCarRepair
 */
CarRepair.prototype.stateCarRepair = undefined;

