/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Car} from './Car';
import {User} from './User';

/**
 * The ClientCar model module.
 * @module model/ClientCar
 * @version v1
 */
export class ClientCar {
  /**
   * Constructs a new <code>ClientCar</code>.
   * @alias module:model/ClientCar
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ClientCar</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientCar} obj Optional instance to populate.
   * @return {module:model/ClientCar} The populated <code>ClientCar</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClientCar();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('registerNumber'))
        obj.registerNumber = ApiClient.convertToType(data['registerNumber'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('user'))
        obj.user = User.constructFromObject(data['user']);
      if (data.hasOwnProperty('carId'))
        obj.carId = ApiClient.convertToType(data['carId'], 'Number');
      if (data.hasOwnProperty('car'))
        obj.car = Car.constructFromObject(data['car']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ClientCar.prototype.id = undefined;

/**
 * @member {String} registerNumber
 */
ClientCar.prototype.registerNumber = undefined;

/**
 * @member {Number} userId
 */
ClientCar.prototype.userId = undefined;

/**
 * @member {module:model/User} user
 */
ClientCar.prototype.user = undefined;

/**
 * @member {Number} carId
 */
ClientCar.prototype.carId = undefined;

/**
 * @member {module:model/Car} car
 */
ClientCar.prototype.car = undefined;

