/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Car} from './Car';
import {CarRepair} from './CarRepair';
import {User} from './User';

/**
 * The GetCarRepairDto model module.
 * @module model/GetCarRepairDto
 * @version v1
 */
export class GetCarRepairDto {
  /**
   * Constructs a new <code>GetCarRepairDto</code>.
   * @alias module:model/GetCarRepairDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetCarRepairDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCarRepairDto} obj Optional instance to populate.
   * @return {module:model/GetCarRepairDto} The populated <code>GetCarRepairDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetCarRepairDto();
      if (data.hasOwnProperty('carRepair'))
        obj.carRepair = CarRepair.constructFromObject(data['carRepair']);
      if (data.hasOwnProperty('car'))
        obj.car = Car.constructFromObject(data['car']);
      if (data.hasOwnProperty('carUser'))
        obj.carUser = User.constructFromObject(data['carUser']);
      if (data.hasOwnProperty('emp'))
        obj.emp = User.constructFromObject(data['emp']);
    }
    return obj;
  }
}

/**
 * @member {module:model/CarRepair} carRepair
 */
GetCarRepairDto.prototype.carRepair = undefined;

/**
 * @member {module:model/Car} car
 */
GetCarRepairDto.prototype.car = undefined;

/**
 * @member {module:model/User} carUser
 */
GetCarRepairDto.prototype.carUser = undefined;

/**
 * @member {module:model/User} emp
 */
GetCarRepairDto.prototype.emp = undefined;

