/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ImgDto} from './ImgDto';

/**
 * The GetNewDto model module.
 * @module model/GetNewDto
 * @version v1
 */
export class GetNewDto {
  /**
   * Constructs a new <code>GetNewDto</code>.
   * @alias module:model/GetNewDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetNewDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetNewDto} obj Optional instance to populate.
   * @return {module:model/GetNewDto} The populated <code>GetNewDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetNewDto();
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('createdDate'))
        obj.createdDate = ApiClient.convertToType(data['createdDate'], 'Date');
      if (data.hasOwnProperty('isDeleted'))
        obj.isDeleted = ApiClient.convertToType(data['isDeleted'], 'Boolean');
      if (data.hasOwnProperty('firstName'))
        obj.firstName = ApiClient.convertToType(data['firstName'], 'String');
      if (data.hasOwnProperty('lastName'))
        obj.lastName = ApiClient.convertToType(data['lastName'], 'String');
      if (data.hasOwnProperty('imgs'))
        obj.imgs = ApiClient.convertToType(data['imgs'], [ImgDto]);
    }
    return obj;
  }
}

/**
 * @member {String} title
 */
GetNewDto.prototype.title = undefined;

/**
 * @member {String} description
 */
GetNewDto.prototype.description = undefined;

/**
 * @member {Date} createdDate
 */
GetNewDto.prototype.createdDate = undefined;

/**
 * @member {Boolean} isDeleted
 */
GetNewDto.prototype.isDeleted = undefined;

/**
 * @member {String} firstName
 */
GetNewDto.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
GetNewDto.prototype.lastName = undefined;

/**
 * @member {Array.<module:model/ImgDto>} imgs
 */
GetNewDto.prototype.imgs = undefined;

