/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ClientCar} from './ClientCar';
import {Order} from './Order';

/**
 * The GetOrderBuyerDto model module.
 * @module model/GetOrderBuyerDto
 * @version v1
 */
export class GetOrderBuyerDto {
  /**
   * Constructs a new <code>GetOrderBuyerDto</code>.
   * @alias module:model/GetOrderBuyerDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetOrderBuyerDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetOrderBuyerDto} obj Optional instance to populate.
   * @return {module:model/GetOrderBuyerDto} The populated <code>GetOrderBuyerDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetOrderBuyerDto();
      if (data.hasOwnProperty('order'))
        obj.order = Order.constructFromObject(data['order']);
      if (data.hasOwnProperty('clientCar'))
        obj.clientCar = ClientCar.constructFromObject(data['clientCar']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Order} order
 */
GetOrderBuyerDto.prototype.order = undefined;

/**
 * @member {module:model/ClientCar} clientCar
 */
GetOrderBuyerDto.prototype.clientCar = undefined;

