/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GetCarDto} from './GetCarDto';

/**
 * The GetPagedCarDto model module.
 * @module model/GetPagedCarDto
 * @version v1
 */
export class GetPagedCarDto {
  /**
   * Constructs a new <code>GetPagedCarDto</code>.
   * @alias module:model/GetPagedCarDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetPagedCarDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetPagedCarDto} obj Optional instance to populate.
   * @return {module:model/GetPagedCarDto} The populated <code>GetPagedCarDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetPagedCarDto();
      if (data.hasOwnProperty('getCarDto'))
        obj.getCarDto = ApiClient.convertToType(data['getCarDto'], [GetCarDto]);
      if (data.hasOwnProperty('totalCount'))
        obj.totalCount = ApiClient.convertToType(data['totalCount'], 'Number');
      if (data.hasOwnProperty('pageSize'))
        obj.pageSize = ApiClient.convertToType(data['pageSize'], 'Number');
      if (data.hasOwnProperty('currentPage'))
        obj.currentPage = ApiClient.convertToType(data['currentPage'], 'Number');
      if (data.hasOwnProperty('totalPages'))
        obj.totalPages = ApiClient.convertToType(data['totalPages'], 'Number');
      if (data.hasOwnProperty('hasNext'))
        obj.hasNext = ApiClient.convertToType(data['hasNext'], 'Boolean');
      if (data.hasOwnProperty('hasPrevious'))
        obj.hasPrevious = ApiClient.convertToType(data['hasPrevious'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/GetCarDto>} getCarDto
 */
GetPagedCarDto.prototype.getCarDto = undefined;

/**
 * @member {Number} totalCount
 */
GetPagedCarDto.prototype.totalCount = undefined;

/**
 * @member {Number} pageSize
 */
GetPagedCarDto.prototype.pageSize = undefined;

/**
 * @member {Number} currentPage
 */
GetPagedCarDto.prototype.currentPage = undefined;

/**
 * @member {Number} totalPages
 */
GetPagedCarDto.prototype.totalPages = undefined;

/**
 * @member {Boolean} hasNext
 */
GetPagedCarDto.prototype.hasNext = undefined;

/**
 * @member {Boolean} hasPrevious
 */
GetPagedCarDto.prototype.hasPrevious = undefined;

