/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GetUserDto model module.
 * @module model/GetUserDto
 * @version v1
 */
export class GetUserDto {
  /**
   * Constructs a new <code>GetUserDto</code>.
   * @alias module:model/GetUserDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GetUserDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetUserDto} obj Optional instance to populate.
   * @return {module:model/GetUserDto} The populated <code>GetUserDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GetUserDto();
      if (data.hasOwnProperty('firstName'))
        obj.firstName = ApiClient.convertToType(data['firstName'], 'String');
      if (data.hasOwnProperty('lastName'))
        obj.lastName = ApiClient.convertToType(data['lastName'], 'String');
      if (data.hasOwnProperty('surname'))
        obj.surname = ApiClient.convertToType(data['surname'], 'String');
      if (data.hasOwnProperty('dBay'))
        obj.dBay = ApiClient.convertToType(data['dBay'], 'Date');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('phoneNumber'))
        obj.phoneNumber = ApiClient.convertToType(data['phoneNumber'], 'String');
      if (data.hasOwnProperty('roleName'))
        obj.roleName = ApiClient.convertToType(data['roleName'], 'String');
      if (data.hasOwnProperty('urlPhoto'))
        obj.urlPhoto = ApiClient.convertToType(data['urlPhoto'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} firstName
 */
GetUserDto.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
GetUserDto.prototype.lastName = undefined;

/**
 * @member {String} surname
 */
GetUserDto.prototype.surname = undefined;

/**
 * @member {Date} dBay
 */
GetUserDto.prototype.dBay = undefined;

/**
 * @member {String} status
 */
GetUserDto.prototype.status = undefined;

/**
 * @member {String} email
 */
GetUserDto.prototype.email = undefined;

/**
 * @member {String} phoneNumber
 */
GetUserDto.prototype.phoneNumber = undefined;

/**
 * @member {String} roleName
 */
GetUserDto.prototype.roleName = undefined;

/**
 * @member {String} urlPhoto
 */
GetUserDto.prototype.urlPhoto = undefined;

