/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Car} from './Car';
import {State} from './State';
import {User} from './User';

/**
 * The Order model module.
 * @module model/Order
 * @version v1
 */
export class Order {
  /**
   * Constructs a new <code>Order</code>.
   * @alias module:model/Order
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Order} obj Optional instance to populate.
   * @return {module:model/Order} The populated <code>Order</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Order();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('totalCost'))
        obj.totalCost = ApiClient.convertToType(data['totalCost'], 'Number');
      if (data.hasOwnProperty('dateOfBuyCar'))
        obj.dateOfBuyCar = ApiClient.convertToType(data['dateOfBuyCar'], 'Date');
      if (data.hasOwnProperty('carId'))
        obj.carId = ApiClient.convertToType(data['carId'], 'Number');
      if (data.hasOwnProperty('car'))
        obj.car = Car.constructFromObject(data['car']);
      if (data.hasOwnProperty('state'))
        obj.state = State.constructFromObject(data['state']);
      if (data.hasOwnProperty('user'))
        obj.user = User.constructFromObject(data['user']);
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('changeRegisterNumber'))
        obj.changeRegisterNumber = ApiClient.convertToType(data['changeRegisterNumber'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Order.prototype.id = undefined;

/**
 * @member {Number} totalCost
 */
Order.prototype.totalCost = undefined;

/**
 * @member {Date} dateOfBuyCar
 */
Order.prototype.dateOfBuyCar = undefined;

/**
 * @member {Number} carId
 */
Order.prototype.carId = undefined;

/**
 * @member {module:model/Car} car
 */
Order.prototype.car = undefined;

/**
 * @member {module:model/State} state
 */
Order.prototype.state = undefined;

/**
 * @member {module:model/User} user
 */
Order.prototype.user = undefined;

/**
 * @member {Number} userId
 */
Order.prototype.userId = undefined;

/**
 * @member {Boolean} changeRegisterNumber
 */
Order.prototype.changeRegisterNumber = undefined;

