/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PostCarDto} from './PostCarDto';

/**
 * The PostClientCarDto model module.
 * @module model/PostClientCarDto
 * @version v1
 */
export class PostClientCarDto {
  /**
   * Constructs a new <code>PostClientCarDto</code>.
   * @alias module:model/PostClientCarDto
   * @class
   * @param postCarDto {module:model/PostCarDto} 
   * @param email {String} 
   */
  constructor(postCarDto, email) {
    this.postCarDto = postCarDto;
    this.email = email;
  }

  /**
   * Constructs a <code>PostClientCarDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostClientCarDto} obj Optional instance to populate.
   * @return {module:model/PostClientCarDto} The populated <code>PostClientCarDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostClientCarDto();
      if (data.hasOwnProperty('postCarDto'))
        obj.postCarDto = PostCarDto.constructFromObject(data['postCarDto']);
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('registerNumber'))
        obj.registerNumber = ApiClient.convertToType(data['registerNumber'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/PostCarDto} postCarDto
 */
PostClientCarDto.prototype.postCarDto = undefined;

/**
 * @member {String} email
 */
PostClientCarDto.prototype.email = undefined;

/**
 * @member {String} registerNumber
 */
PostClientCarDto.prototype.registerNumber = undefined;

