/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CarEquipmentFormItemDto} from './CarEquipmentFormItemDto';

/**
 * The PostCarEquipmentDto model module.
 * @module model/PostCarEquipmentDto
 * @version v1
 */
export class PostCarEquipmentDto {
  /**
   * Constructs a new <code>PostCarEquipmentDto</code>.
   * @alias module:model/PostCarEquipmentDto
   * @class
   * @param name {String} 
   * @param equipments {Array.<module:model/CarEquipmentFormItemDto>} 
   */
  constructor(name, equipments) {
    this.name = name;
    this.equipments = equipments;
  }

  /**
   * Constructs a <code>PostCarEquipmentDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostCarEquipmentDto} obj Optional instance to populate.
   * @return {module:model/PostCarEquipmentDto} The populated <code>PostCarEquipmentDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostCarEquipmentDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('equipments'))
        obj.equipments = ApiClient.convertToType(data['equipments'], [CarEquipmentFormItemDto]);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
PostCarEquipmentDto.prototype.name = undefined;

/**
 * @member {Array.<module:model/CarEquipmentFormItemDto>} equipments
 */
PostCarEquipmentDto.prototype.equipments = undefined;

