/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ValueCarEquipmentDto} from './ValueCarEquipmentDto';

/**
 * The PostCarEquipmentFormDto model module.
 * @module model/PostCarEquipmentFormDto
 * @version v1
 */
export class PostCarEquipmentFormDto {
  /**
   * Constructs a new <code>PostCarEquipmentFormDto</code>.
   * @alias module:model/PostCarEquipmentFormDto
   * @class
   * @param name {String} 
   * @param equipmentItems {Array.<module:model/ValueCarEquipmentDto>} 
   */
  constructor(name, equipmentItems) {
    this.name = name;
    this.equipmentItems = equipmentItems;
  }

  /**
   * Constructs a <code>PostCarEquipmentFormDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostCarEquipmentFormDto} obj Optional instance to populate.
   * @return {module:model/PostCarEquipmentFormDto} The populated <code>PostCarEquipmentFormDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostCarEquipmentFormDto();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('equipmentItems'))
        obj.equipmentItems = ApiClient.convertToType(data['equipmentItems'], [ValueCarEquipmentDto]);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
PostCarEquipmentFormDto.prototype.name = undefined;

/**
 * @member {Array.<module:model/ValueCarEquipmentDto>} equipmentItems
 */
PostCarEquipmentFormDto.prototype.equipmentItems = undefined;

