/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The PostCarRepairDto model module.
 * @module model/PostCarRepairDto
 * @version v1
 */
export class PostCarRepairDto {
  /**
   * Constructs a new <code>PostCarRepairDto</code>.
   * @alias module:model/PostCarRepairDto
   * @class
   * @param description {String} 
   * @param vin {String} 
   * @param email {String} 
   * @param emailOwner {String} 
   */
  constructor(description, vin, email, emailOwner) {
    this.description = description;
    this.vin = vin;
    this.email = email;
    this.emailOwner = emailOwner;
  }

  /**
   * Constructs a <code>PostCarRepairDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostCarRepairDto} obj Optional instance to populate.
   * @return {module:model/PostCarRepairDto} The populated <code>PostCarRepairDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostCarRepairDto();
      if (data.hasOwnProperty("description"))
        obj.description = ApiClient.convertToType(
          data["description"],
          "String"
        );
      if (data.hasOwnProperty("vin"))
        obj.vin = ApiClient.convertToType(data["vin"], "String");
      if (data.hasOwnProperty("email"))
        obj.email = ApiClient.convertToType(data["email"], "String");
      if (data.hasOwnProperty("emailOwner"))
        obj.emailOwner = ApiClient.convertToType(data["emailOwner"], "String");
    }
    return obj;
  }
}

/**
 * @member {String} description
 */
PostCarRepairDto.prototype.description = undefined;

/**
 * @member {String} vin
 */
PostCarRepairDto.prototype.vin = undefined;

/**
 * @member {String} email
 */
PostCarRepairDto.prototype.email = undefined;

/**
 * @member {String} emailOwner
 */
PostCarRepairDto.prototype.emailOwner = undefined;
