/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PostUserDto model module.
 * @module model/PostUserDto
 * @version v1
 */
export class PostUserDto {
  /**
   * Constructs a new <code>PostUserDto</code>.
   * @alias module:model/PostUserDto
   * @class
   * @param firstName {String} 
   * @param lastName {String} 
   * @param urlPhoto {String} 
   * @param surname {String} 
   * @param dBay {Date} 
   * @param password {String} 
   * @param email {String} 
   * @param phoneNumber {String} 
   */
  constructor(firstName, lastName, urlPhoto, surname, dBay, password, email, phoneNumber) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.urlPhoto = urlPhoto;
    this.surname = surname;
    this.dBay = dBay;
    this.password = password;
    this.email = email;
    this.phoneNumber = phoneNumber;
  }

  /**
   * Constructs a <code>PostUserDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostUserDto} obj Optional instance to populate.
   * @return {module:model/PostUserDto} The populated <code>PostUserDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostUserDto();
      if (data.hasOwnProperty('firstName'))
        obj.firstName = ApiClient.convertToType(data['firstName'], 'String');
      if (data.hasOwnProperty('lastName'))
        obj.lastName = ApiClient.convertToType(data['lastName'], 'String');
      if (data.hasOwnProperty('urlPhoto'))
        obj.urlPhoto = ApiClient.convertToType(data['urlPhoto'], 'String');
      if (data.hasOwnProperty('surname'))
        obj.surname = ApiClient.convertToType(data['surname'], 'String');
      if (data.hasOwnProperty('dBay'))
        obj.dBay = ApiClient.convertToType(data['dBay'], 'Date');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('phoneNumber'))
        obj.phoneNumber = ApiClient.convertToType(data['phoneNumber'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} firstName
 */
PostUserDto.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
PostUserDto.prototype.lastName = undefined;

/**
 * @member {String} urlPhoto
 */
PostUserDto.prototype.urlPhoto = undefined;

/**
 * @member {String} surname
 */
PostUserDto.prototype.surname = undefined;

/**
 * @member {Date} dBay
 */
PostUserDto.prototype.dBay = undefined;

/**
 * @member {String} password
 */
PostUserDto.prototype.password = undefined;

/**
 * @member {String} email
 */
PostUserDto.prototype.email = undefined;

/**
 * @member {String} phoneNumber
 */
PostUserDto.prototype.phoneNumber = undefined;

