/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";
import { ImgDto } from "./ImgDto";
import { PostNewDto } from "./PostNewDto";

/**
 * The PostNewDtoNewWrapperDto model module.
 * @module model/PostNewDtoNewWrapperDto
 * @version v1
 */
export class PostNewDtoNewWrapperDto {
  /**
   * Constructs a new <code>PostNewDtoNewWrapperDto</code>.
   * @alias module:model/PostNewDtoNewWrapperDto
   * @class
   * @param _new {module:model/PostNewDto} 
   * @param imgs {Array.<module:model/ImgDto>} 
   */
  constructor(_new, imgs) {
    this.New = _new;
    this.imgs = imgs;
  }

  /**
   * Constructs a <code>PostNewDtoNewWrapperDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostNewDtoNewWrapperDto} obj Optional instance to populate.
   * @return {module:model/PostNewDtoNewWrapperDto} The populated <code>PostNewDtoNewWrapperDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PostNewDtoNewWrapperDto();
      if (data.hasOwnProperty("new"))
        obj._new = PostNewDto.constructFromObject(data["new"]);
      if (data.hasOwnProperty("imgs"))
        obj.imgs = ApiClient.convertToType(data["imgs"], [ImgDto]);
    }
    return obj;
  }
}

/**
 * @member {module:model/PostNewDto} _new
 */
PostNewDtoNewWrapperDto.prototype.New = undefined;

/**
 * @member {Array.<module:model/ImgDto>} imgs
 */
PostNewDtoNewWrapperDto.prototype.imgs = undefined;
