/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ImgDto} from './ImgDto';

/**
 * The PutCarDto model module.
 * @module model/PutCarDto
 * @version v1
 */
export class PutCarDto {
  /**
   * Constructs a new <code>PutCarDto</code>.
   * @alias module:model/PutCarDto
   * @class
   * @param nameCarEquipment {String} 
   * @param cost {Number} 
   * @param carMileage {Number} 
   * @param dateOfRealeseCar {Date} 
   * @param imgs {Array.<module:model/ImgDto>} 
   */
  constructor(nameCarEquipment, cost, carMileage, dateOfRealeseCar, imgs) {
    this.nameCarEquipment = nameCarEquipment;
    this.cost = cost;
    this.carMileage = carMileage;
    this.dateOfRealeseCar = dateOfRealeseCar;
    this.imgs = imgs;
  }

  /**
   * Constructs a <code>PutCarDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutCarDto} obj Optional instance to populate.
   * @return {module:model/PutCarDto} The populated <code>PutCarDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutCarDto();
      if (data.hasOwnProperty('nameCarEquipment'))
        obj.nameCarEquipment = ApiClient.convertToType(data['nameCarEquipment'], 'String');
      if (data.hasOwnProperty('cost'))
        obj.cost = ApiClient.convertToType(data['cost'], 'Number');
      if (data.hasOwnProperty('vin'))
        obj.vin = ApiClient.convertToType(data['vin'], 'String');
      if (data.hasOwnProperty('newVIN'))
        obj.newVIN = ApiClient.convertToType(data['newVIN'], 'String');
      if (data.hasOwnProperty('carMileage'))
        obj.carMileage = ApiClient.convertToType(data['carMileage'], 'Number');
      if (data.hasOwnProperty('dateOfRealeseCar'))
        obj.dateOfRealeseCar = ApiClient.convertToType(data['dateOfRealeseCar'], 'Date');
      if (data.hasOwnProperty('sharePercentage'))
        obj.sharePercentage = ApiClient.convertToType(data['sharePercentage'], 'Number');
      if (data.hasOwnProperty('imgs'))
        obj.imgs = ApiClient.convertToType(data['imgs'], [ImgDto]);
    }
    return obj;
  }
}

/**
 * @member {String} nameCarEquipment
 */
PutCarDto.prototype.nameCarEquipment = undefined;

/**
 * @member {Number} cost
 */
PutCarDto.prototype.cost = undefined;

/**
 * @member {String} vin
 */
PutCarDto.prototype.vin = undefined;

/**
 * @member {String} newVIN
 */
PutCarDto.prototype.newVIN = undefined;

/**
 * @member {Number} carMileage
 */
PutCarDto.prototype.carMileage = undefined;

/**
 * @member {Date} dateOfRealeseCar
 */
PutCarDto.prototype.dateOfRealeseCar = undefined;

/**
 * @member {Number} sharePercentage
 */
PutCarDto.prototype.sharePercentage = undefined;

/**
 * @member {Array.<module:model/ImgDto>} imgs
 */
PutCarDto.prototype.imgs = undefined;

