/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PutNewDto model module.
 * @module model/PutNewDto
 * @version v1
 */
export class PutNewDto {
  /**
   * Constructs a new <code>PutNewDto</code>.
   * @alias module:model/PutNewDto
   * @class
   * @param title {String} 
   * @param description {String} 
   */
  constructor(title, description) {
    this.title = title;
    this.description = description;
  }

  /**
   * Constructs a <code>PutNewDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutNewDto} obj Optional instance to populate.
   * @return {module:model/PutNewDto} The populated <code>PutNewDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutNewDto();
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('newTitle'))
        obj.newTitle = ApiClient.convertToType(data['newTitle'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} title
 */
PutNewDto.prototype.title = undefined;

/**
 * @member {String} newTitle
 */
PutNewDto.prototype.newTitle = undefined;

/**
 * @member {String} description
 */
PutNewDto.prototype.description = undefined;

