/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ImgDto} from './ImgDto';
import {PutNewDto} from './PutNewDto';

/**
 * The PutNewDtoNewWrapperDto model module.
 * @module model/PutNewDtoNewWrapperDto
 * @version v1
 */
export class PutNewDtoNewWrapperDto {
  /**
   * Constructs a new <code>PutNewDtoNewWrapperDto</code>.
   * @alias module:model/PutNewDtoNewWrapperDto
   * @class
   * @param _new {module:model/PutNewDto} 
   * @param imgs {Array.<module:model/ImgDto>} 
   */
  constructor(_new, imgs) {
    this._new = _new;
    this.imgs = imgs;
  }

  /**
   * Constructs a <code>PutNewDtoNewWrapperDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutNewDtoNewWrapperDto} obj Optional instance to populate.
   * @return {module:model/PutNewDtoNewWrapperDto} The populated <code>PutNewDtoNewWrapperDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PutNewDtoNewWrapperDto();
      if (data.hasOwnProperty('new'))
        obj._new = PutNewDto.constructFromObject(data['new']);
      if (data.hasOwnProperty('imgs'))
        obj.imgs = ApiClient.convertToType(data['imgs'], [ImgDto]);
    }
    return obj;
  }
}

/**
 * @member {module:model/PutNewDto} _new
 */
PutNewDtoNewWrapperDto.prototype._new = undefined;

/**
 * @member {Array.<module:model/ImgDto>} imgs
 */
PutNewDtoNewWrapperDto.prototype.imgs = undefined;

