/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TestDriveDto model module.
 * @module model/TestDriveDto
 * @version v1
 */
export class TestDriveDto {
  /**
   * Constructs a new <code>TestDriveDto</code>.
   * @alias module:model/TestDriveDto
   * @class
   * @param dateStart {Date} 
   * @param time {Number} 
   * @param email {String} 
   * @param vin {String} 
   */
  constructor(dateStart, time, email, vin) {
    this.dateStart = dateStart;
    this.time = time;
    this.email = email;
    this.vin = vin;
  }

  /**
   * Constructs a <code>TestDriveDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TestDriveDto} obj Optional instance to populate.
   * @return {module:model/TestDriveDto} The populated <code>TestDriveDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TestDriveDto();
      if (data.hasOwnProperty('dateStart'))
        obj.dateStart = ApiClient.convertToType(data['dateStart'], 'Date');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'Number');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('vin'))
        obj.vin = ApiClient.convertToType(data['vin'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Date} dateStart
 */
TestDriveDto.prototype.dateStart = undefined;

/**
 * @member {Number} time
 */
TestDriveDto.prototype.time = undefined;

/**
 * @member {String} email
 */
TestDriveDto.prototype.email = undefined;

/**
 * @member {String} vin
 */
TestDriveDto.prototype.vin = undefined;

