/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The UpdateStateOrderDto model module.
 * @module model/UpdateStateOrderDto
 * @version v1
 */
export class UpdateStateOrderDto {
  /**
   * Constructs a new <code>UpdateStateOrderDto</code>.
   * @alias module:model/UpdateStateOrderDto
   * @class
   * @param vin {String} 
   * @param emailBuyer {String} 
   */
  constructor(vin, emailBuyer, totalCost) {
    this.vin = vin;
    this.totalCost = totalCost;
    this.emailBuyer = emailBuyer;
  }

  /**
   * Constructs a <code>UpdateStateOrderDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateStateOrderDto} obj Optional instance to populate.
   * @return {module:model/UpdateStateOrderDto} The populated <code>UpdateStateOrderDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateStateOrderDto();
      if (data.hasOwnProperty("vin"))
        obj.vin = ApiClient.convertToType(data["vin"], "String");
      if (data.hasOwnProperty("emailBuyer"))
        obj.emailBuyer = ApiClient.convertToType(data["emailBuyer"], "String");
      if (data.hasOwnProperty("totalCost"))
        obj.totalCost = ApiClient.convertToType(data["totalCost"], "Number");
    }
    return obj;
  }
}

/**
 * @member {String} vin
 */
UpdateStateOrderDto.prototype.vin = undefined;

/**
 * @member {String} emailBuyer
 */
UpdateStateOrderDto.prototype.emailBuyer = undefined;

/**
 * @member {Number} totalCost
 */
UpdateStateOrderDto.prototype.totalCost = undefined;
