/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UpdateStateCarRepairForStartWorkDto model module.
 * @module model/UpdateStateCarRepairForStartWorkDto
 * @version v1
 */
export class UpdateStateCarRepairForStartWorkDto {
  /**
   * Constructs a new <code>UpdateStateCarRepairForStartWorkDto</code>.
   * @alias module:model/UpdateStateCarRepairForStartWorkDto
   * @class
   * @param emailEmployee {String} 
   * @param vin {String} 
   */
  constructor(emailEmployee, vin) {
    this.emailEmployee = emailEmployee;
    this.vin = vin;
  }

  /**
   * Constructs a <code>UpdateStateCarRepairForStartWorkDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateStateCarRepairForStartWorkDto} obj Optional instance to populate.
   * @return {module:model/UpdateStateCarRepairForStartWorkDto} The populated <code>UpdateStateCarRepairForStartWorkDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateStateCarRepairForStartWorkDto();
      if (data.hasOwnProperty('emailEmployee'))
        obj.emailEmployee = ApiClient.convertToType(data['emailEmployee'], 'String');
      if (data.hasOwnProperty('vin'))
        obj.vin = ApiClient.convertToType(data['vin'], 'String');
      if (data.hasOwnProperty('startWork'))
        obj.startWork = ApiClient.convertToType(data['startWork'], 'Date');
      if (data.hasOwnProperty('endWork'))
        obj.endWork = ApiClient.convertToType(data['endWork'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} emailEmployee
 */
UpdateStateCarRepairForStartWorkDto.prototype.emailEmployee = undefined;

/**
 * @member {String} vin
 */
UpdateStateCarRepairForStartWorkDto.prototype.vin = undefined;

/**
 * @member {Date} startWork
 */
UpdateStateCarRepairForStartWorkDto.prototype.startWork = undefined;

/**
 * @member {Date} endWork
 */
UpdateStateCarRepairForStartWorkDto.prototype.endWork = undefined;

