/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../ApiClient";

/**
 * The UpdateStateOrderForPaidDto model module.
 * @module model/UpdateStateOrderForPaidDto
 * @version v1
 */
export class UpdateStateOrderForPaidDto {
  /**
   * Constructs a new <code>UpdateStateOrderForPaidDto</code>.
   * @alias module:model/UpdateStateOrderForPaidDto
   * @class
   * @param vin {String} 
   * @param emailBuyer {String} 
   * @param totalCost {Number} 
   * @param cardNumber {String} 
   * @param month {Number} 
   * @param year {Number} 
   * @param cvc {Number} 
   * @param cardOwnerName {String} 
   */
  constructor(
    vin,
    emailBuyer,
    totalCost,
    cardNumber,
    month,
    year,
    cvc,
    cardOwnerName
  ) {
    this.vin = vin;
    this.emailBuyer = emailBuyer;
    this.totalCost = totalCost;
    this.cardNumber = cardNumber;
    this.month = month;
    this.year = year;
    this.cvc = cvc;
    this.cardOwnerName = cardOwnerName;
  }

  /**
   * Constructs a <code>UpdateStateOrderForPaidDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateStateOrderForPaidDto} obj Optional instance to populate.
   * @return {module:model/UpdateStateOrderForPaidDto} The populated <code>UpdateStateOrderForPaidDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateStateOrderForPaidDto();
      if (data.hasOwnProperty("vin"))
        obj.vin = ApiClient.convertToType(data["vin"], "String");
      if (data.hasOwnProperty("emailBuyer"))
        obj.emailBuyer = ApiClient.convertToType(data["emailBuyer"], "String");
      if (data.hasOwnProperty("totalCost"))
        obj.totalCost = ApiClient.convertToType(data["totalCost"], "Number");
      if (data.hasOwnProperty("cardNumber"))
        obj.cardNumber = ApiClient.convertToType(data["cardNumber"], "String");
      if (data.hasOwnProperty("month"))
        obj.month = ApiClient.convertToType(data["month"], "Number");
      if (data.hasOwnProperty("year"))
        obj.year = ApiClient.convertToType(data["year"], "Number");
      if (data.hasOwnProperty("cvc"))
        obj.cvc = ApiClient.convertToType(data["cvc"], "Number");
      if (data.hasOwnProperty("cardOwnerName"))
        obj.cardOwnerName = ApiClient.convertToType(
          data["cardOwnerName"],
          "String"
        );
    }
    return obj;
  }
}

/**
 * @member {String} vin
 */
UpdateStateOrderForPaidDto.prototype.vin = undefined;

/**
 * @member {String} emailBuyer
 */
UpdateStateOrderForPaidDto.prototype.emailBuyer = undefined;

/**
 * @member {Number} totalCost
 */
UpdateStateOrderForPaidDto.prototype.totalCost = undefined;

/**
 * @member {String} cardNumber
 */
UpdateStateOrderForPaidDto.prototype.cardNumber = undefined;

/**
 * @member {Number} month
 */
UpdateStateOrderForPaidDto.prototype.month = undefined;

/**
 * @member {Number} year
 */
UpdateStateOrderForPaidDto.prototype.year = undefined;

/**
 * @member {Number} cvc
 */
UpdateStateOrderForPaidDto.prototype.cvc = undefined;

/**
 * @member {String} cardOwnerName
 */
UpdateStateOrderForPaidDto.prototype.cardOwnerName = undefined;
