/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ValueCarEquipmentDto model module.
 * @module model/ValueCarEquipmentDto
 * @version v1
 */
export class ValueCarEquipmentDto {
  /**
   * Constructs a new <code>ValueCarEquipmentDto</code>.
   * @alias module:model/ValueCarEquipmentDto
   * @class
   * @param value {String} 
   * @param cost {Number} 
   */
  constructor(value, cost) {
    this.value = value;
    this.cost = cost;
  }

  /**
   * Constructs a <code>ValueCarEquipmentDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ValueCarEquipmentDto} obj Optional instance to populate.
   * @return {module:model/ValueCarEquipmentDto} The populated <code>ValueCarEquipmentDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ValueCarEquipmentDto();
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
      if (data.hasOwnProperty('cost'))
        obj.cost = ApiClient.convertToType(data['cost'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} value
 */
ValueCarEquipmentDto.prototype.value = undefined;

/**
 * @member {Number} cost
 */
ValueCarEquipmentDto.prototype.cost = undefined;

