/*
 * BackEndAutoCenterVw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ValueCarEquipment model module.
 * @module model/ValueCarEquipment
 * @version v1
 */
export class ValueCarEquipment {
  /**
   * Constructs a new <code>ValueCarEquipment</code>.
   * @alias module:model/ValueCarEquipment
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ValueCarEquipment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ValueCarEquipment} obj Optional instance to populate.
   * @return {module:model/ValueCarEquipment} The populated <code>ValueCarEquipment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ValueCarEquipment();
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
      if (data.hasOwnProperty('cost'))
        obj.cost = ApiClient.convertToType(data['cost'], 'Number');
      if (data.hasOwnProperty('isDeleted'))
        obj.isDeleted = ApiClient.convertToType(data['isDeleted'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} value
 */
ValueCarEquipment.prototype.value = undefined;

/**
 * @member {Number} cost
 */
ValueCarEquipment.prototype.cost = undefined;

/**
 * @member {Boolean} isDeleted
 */
ValueCarEquipment.prototype.isDeleted = undefined;

